import type { JsonRecord } from "@/api/types/common.types";
import { DEFAULT_TALK_TO_AGENT_BUTTON_LABEL } from "./talk-to-agent.constants";
import { normalizeWidgetInquiryOptions } from "./widget-inquiry.types";

/** Defaults for PATCH slices not yet exposed in the add-widget UI (aligned with backend BOTH example). */
export const CHAT_WIZARD_PATCH_DEFAULTS = {
  themeName: "Brand Default",
  themeSecondaryColor: "#64748b",
  themeFontFamily: "Inter, system-ui, sans-serif",
  themeBubbleStyle: "rounded",
  themeBorderRadiusPx: 12,
  themeWelcomeFontSizePx: 18,
  themeBodyFontSizePx: 14,
  themeInputFontSizePx: 14,
  themeCtaFontSizePx: 15,
  themeConsentFontSizePx: 12,
  themeLineHeightPx: 22,
  designJsonAccent: "blue",
  designJsonDensity: "comfortable",
  buttonLabel: "Chat with us",
  proactiveTeaser: "Any questions? Let us know!",
  proactiveSecondaryCtaLabel: "Contact us on WhatsApp",
  proactiveSecondaryCtaHref: "https://wa.me/",
  firstMessage: "Hi! How can we help today?",
  messagePlaceholder: "Write here…",
  backgroundColor: "#f8fafc",
  popupEnabled: false,
  botEnabled: true,
  notificationEnabled: true,
  inquiryOptions: normalizeWidgetInquiryOptions(["Billing", "Technical", "Sales"]),
  inquiryRequired: false,
  inquirySkipLabel: "General question",
  welcomeMessage: "Thanks for reaching out.",
  autoOpenEnabled: false,
  autoOpenDelaySeconds: 10,
  autoOpenOnReturnVisit: false,
  notificationSoundId: "chime" as const,
  launcherBadgeMode: "count" as const,
  fileUploadEnabled: true,
  emojiEnabled: true,
  consentRequired: true,
  consentText: "I agree to the chat terms and privacy policy.",
  privacyPolicyUrl: "https://www.example.com/privacy",
  privacyNotice: "We process messages per our privacy policy.",
  allowedDomainsText: "Only use this widget on approved domains.",
  persistVisitorSession: true,
  sessionTtlMinutes: 120,
  formEnabled: true,
  formTitle: "Before we start",
  formSubtitle: "Tell us who you are",
  formSubmitLabel: "Start chat",
  prechatNameEnabled: true,
  prechatEmailEnabled: true,
  prechatPhoneEnabled: false,
  prechatMessageEnabled: true,
  prechatMessageRequired: false,
  offlineFormEnabled: true,
  offlineFormTitle: "Leave us a message",
  offlineFormSubtitle: "We're away right now — tell us how we can help.",
  offlineFormSubmitLabel: "Send message",
  offlinePrechatNameEnabled: true,
  offlinePrechatEmailEnabled: true,
  offlinePrechatPhoneEnabled: false,
  offlinePrechatMessageEnabled: true,
  offlinePrechatMessageRequired: true,
  responseWelcomeMessage: "Hello! A teammate will join shortly.",
  responseOfflineMessage: "We are offline; leave a message and we will reply.",
  responseGreetingMessage: "Good day!",
  responseSendPlaceholder: "Ask us anything…",
  responseAiPromptHint: "Be concise and helpful.",
  responseTalkToAgentEnabled: true,
  responseTalkToAgentTriggerText: DEFAULT_TALK_TO_AGENT_BUTTON_LABEL,
};

export function defaultWizardFormFields(): JsonRecord[] {
  return [
    { key: "company", label: "Company", fieldType: "text", required: false, options: [] },
    { key: "topic", label: "Topic", fieldType: "select", required: true, options: ["Order", "Refund", "Other"] },
  ];
}
